Using getopts

diff --git a/overlay/usr/local/bin/bcg-svc-finish b/overlay/usr/local/bin/bcg-svc-finish
--- a/overlay/usr/local/bin/bcg-svc-finish
+++ b/overlay/usr/local/bin/bcg-svc-finish
@@ -4,12 +4,34 @@ set -euo pipefail
 
 
 #======================================================================================================================
-# Check argument.
-#   1   Service name
+# Executable usage.
 #======================================================================================================================
 
-[[ -z "${1-}" ]] && bcg-error "You must provide the name of the service." "bcg-svc-finish"
-NAME=${1}
+usage () {
+    echo "Usage: `basename ${0}` -s SERVICE_NAME [-t] [-h]" 2>&1
+    echo "    -s    The name of the service closing down."
+    echo "    -t    If set, all other services will be terminated."
+    echo "    -h    Shows this usage message."
+    exit 2
+}
+
+
+#======================================================================================================================
+# Flags
+#   -s  Service name
+#   -t  Terminate all services
+#======================================================================================================================
+
+while getopts ":hs:t" C ; do
+    case ${C} in
+        h) usage ;;
+        s) NAME=${OPTARG} ;;
+        t) TERMINATE=1 ;;
+        ?) echo "Invalid option: -${OPTARG}" && usage ;;
+    esac
+done
+
+[[ -z "${NAME-}" ]] && bcg-error "You must provide the name of the service." "bcg-svc-finish"
 
 
 #======================================================================================================================
@@ -23,9 +45,4 @@ bcg-debug "Service closing down." "${NAME}/finish"
 # Terminate all services if the -t flag is set.
 #======================================================================================================================
 
-while getopts 't' C
-do
-  case ${C} in
-    t) bcg-svc-terminate ;;
-  esac
-done
+[[ "${TERMINATE-}" = "1" ]] && bcg-svc-terminate
